### PR TITLE
add twig extension

### PR DESCRIPTION
**Pull request by DavidBadura**

### CODE REVIEW

**Comment by gremo** [comment]
Hi there, first thank you for contributing. 

While your PR is OK for me, I'm stuck at composer.json changes. Why you are suggesting twig/twig when bundle users (using symfony/symfony) already have it as dependency?

Can you aldo modify the README to include the extension usage?

**Comment by DavidBadura** [comment]
First, sorry for the late response. 

To the composer.json changes:

1) You haven't require `symfony/symfony`, only `symfony/framework-bundle` and the bundle don't required it also. The Bundle system is in `symfony/http-kernel` and all application that have these implemented can include bundles. This has nothing to do with Symfony Framework itself. 

2) Symfony don't have a hard dependency to twig. You can use symfony and the bundles without twig. Only the `symfony\standard-edition` required the twig lib :wink:

Yes, i will modify the README.

**Comment by gremo** [comment]
Thanks for your explanation, setup the README and I'll merge.

Thanks for contributing.

**Comment by DavidBadura** [comment]
done :wink:

**Comment by DavidBadura** [comment]
can you also release a new version? :)

**Comment by DavidBadura** [comment]
@gremo ping :wink:

**Comment by gremo** [comment]
Hi, sorry for the delay, I've a lot of work to do in this period.

I've added you as collaborator (it's the first time for me), you should able to push into this repository. Let me know if works as expected, thanks.

**Pull request merged**
